#!/bin/bash
#params  1-> prog name , 2-> input name, 3-->exec number

EXEC_ROOT=$Computer/Program/experiments
INPUT_DIR=$Computer/Program/experiments/input
OUTPUT_DIR=$Computer/Program/experiments/output/$1_$2_K$3_N$4_T$5
Args=2;

case $1 in
	
	meme)
		EXEC_DIR=$EXEC_ROOT/meme/bin
		#export EXEC="/usr/bin/time -a -o $OUTPUT_DIR/timing.txt $EXEC_DIR/meme $INPUT_DIR/fasta/$2.fasta -protein -nmotifs 10 -oc $OUTPUT_DIR"
		EXEC="$EXEC_DIR/meme $INPUT_DIR/fasta/$2.fasta -protein -maxsize 100000000 -w $3 -nmotifs $4 -oc $OUTPUT_DIR"
		;;	
	
	tfem)
		EXEC_DIR=$EXEC_ROOT/TFEM
		#export EXEC="/usr/bin/time -a -o $OUTPUT_DIR/timing.txt $EXEC_DIR/tfem $INPUT_DIR/text/$2.txt .$3"
		EXEC="$EXEC_DIR/tfem $INPUT_DIR/text/$2.txt -k $3 -n $4 -t $5 -o $OUTPUT_DIR/output.csv"
		;;	
	
		
	*)
		echo "Usage:"
		echo "exprun meme|tfem SequenceName KamarWidth NumberOfMotifs Lable"
		echo ""
		echo "Example:"
		echo " > exprun tfem ps00117 12 10 3"
		echo "------> Which runs tfem for ps0017 sequence file to find 10 kamars with 12 width. the results will be stored in tfem_K12_N10_3 folder"
		echo ""
		EXEC=""
		
esac

if [ -d "$OUTPUT_DIR" ]; then
  rm -r $OUTPUT_DIR
fi

if [ "$EXEC" != "" ]; then
	mkdir $OUTPUT_DIR
	echo $EXEC
	/usr/bin/time -f "%e" -a -o $OUTPUT_DIR/timing.txt $EXEC
	cat $OUTPUT_DIR/timing.txt | grep "user"
	echo "Results saved in $OUTPUT_DIR"
fi






